# Generated by Django 3.2 on 2021-10-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filmwork",
            old_name="genres",
            new_name="film_genres",
        ),
    ]
