version: '3.9'
services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build:
      context: .
    ports:
      - 8000:8000
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_value:/static/ 
      - media_value:/media/
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_value:
  media_value: